## Getting Started with NumPy Arrays :

In [1]:
import numpy as np 

In [2]:
print("NumPy version: ", np.__version__)

NumPy version:  2.3.1


In [3]:
arr = np.array([1, 2, 3])              # as the number of square brackets increase , the dimension increases 

np.array(arr)                          # will print the numpy array 

array([1, 2, 3])

### NumPy arrays using built-in functions :

In [4]:
# dimensions and shape of an array  
arr.ndim

1

In [5]:
# shape of an array : (rows, columns)

arr.shape

(3,)

In [6]:
arr2 = np.linspace(0,1,5)   # will create an array of numbers between 0 to 5 with a space of 5
arr2

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
# logarithmic scale array

arr3 = np.logspace(1,3,3)   # (10^1, 10^3, 3 points evenly spaced )
arr3

array([  10.,  100., 1000.])

In [8]:
arr4 = np.zeros(5)   # an array containingg 5 zeroes 
arr4

array([0., 0., 0., 0., 0.])

In [9]:
# Creating a matrix (2D array):

arr5 = np.zeros([2,3])         
arr5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arr6 = np.ones([3,3])      # 3*3 matrix with all the entries as 1
arr6

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# creating an array full of any value 

arr = np.full(10,2)    # 10 2s
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
arr = np.full([3,3], 9)    # ([row, column], default value)
arr

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [13]:
# creating uninitialized array

arr = np.empty([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# generate random floats , uniformly distributed 

arr = np.random.rand(10)
arr

array([0.45927586, 0.5345849 , 0.81974741, 0.24905827, 0.64499278,
       0.38256067, 0.3403598 , 0.42373069, 0.55268734, 0.71442531])

In [15]:
arr =  np.random.rand(3,3)       # do not use square brackets here 
arr

array([[0.09258683, 0.1276121 , 0.26296863],
       [0.7347793 , 0.7439766 , 0.40114843],
       [0.94579941, 0.84392926, 0.47777801]])

In [16]:
# random float from a standard normal distribution ; mean=0, and S.D=1, center is going to be zero

arr = np.random.randn(3,3)
arr

array([[ 1.11702067,  0.42585118,  1.460538  ],
       [ 0.55255601, -0.87874848,  0.63042367],
       [ 0.22566865, -0.54083308,  0.59267863]])

In [17]:
#  Random integers within a range :

arr = np.random.randint(0,21,2)    # (start, stop, dimension/number of values)
arr

array([14, 20], dtype=int32)

In [18]:
arr = np.random.randint(10,100)   
arr

86

In [19]:
arr = np.random.randint(10, 100, size = (3,3))       
arr

array([[97, 31, 43],
       [96, 72, 97],
       [16, 45, 50]], dtype=int32)

### NumPy datatypes and typecasting : 
##### - NumPy arrays do not allow multiple datatypes 

In [20]:
arr = np.array([1,2,3.4,5])
arr

array([1. , 2. , 3.4, 5. ])

In [21]:
print(type(arr))

<class 'numpy.ndarray'>


In [22]:
# convert list into a NumPy array 

lst = ["deepak", 2, 4, 5.67]

np.array(lst)                        # all the elements will get converted to string format

array(['deepak', '2', '4', '5.67'], dtype='<U32')

In [23]:
# converting inter to float

arr = np.array([1, 2, 3, 4, 5], dtype = np.float64)
arr

array([1., 2., 3., 4., 5.])

In [24]:
# Typecasting : whenever you want to convert one type of data into another , 
# astype()

arr = np.array([1, 2, 3])
arr.dtype

dtype('int64')

In [25]:
new_arr = arr.astype(np.float64)
new_arr

array([1., 2., 3.])

##### Creating Multi-dimensional array :

In [26]:
arr = np.array([[1, 2, 3],                  # in an numpy array, only one list is accepted , hence we have to place another square bracket
               [4, 5, 6]])
arr                                         # will print a 2D array

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr.size       # number of elements present 

6

In [28]:
# size of one element in bytes 

arr.itemsize

8

#### Array Reshaping :

In [29]:
# RESHAPE :

arr = np.array([1, 2, 3, 4, 5, 6])
res_arr = arr.reshape(2,3)             # will convert the above 1D array to a 2*3 matrix 
res_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# RAVEL : used to convert any array into 1D array, 
# changes will be reflected in the original array

arr = np.array([[1,2,3],
             [4, 5, 6]])
arr2 = arr.ravel()
arr2

array([1, 2, 3, 4, 5, 6])

In [31]:
# FLATTEN : use to convert any array into 1D array without refelcting the changes in the original array , 
# it will return a copy 

arr = np.array([[1,2,3],
             [4, 5, 6]])
arr2 = arr.flatten()
arr2

array([1, 2, 3, 4, 5, 6])

#### Arithmetic operations on Arrays : 

In [32]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6]) 

In [33]:
# ADDITION : 

arr1 + arr2 


array([5, 7, 9])

In [34]:
#  SUBTRACTION :

arr1 - arr2 

array([-3, -3, -3])

In [35]:
# DIVISION : 

arr1/arr2

array([0.25, 0.4 , 0.5 ])

In [36]:
# MULTIPLICATION : 

arr1 * arr2 

array([ 4, 10, 18])

In [37]:
arr2 // arr1     # will round up the dcimal values , and print integer 

array([4, 2, 2])

In [38]:
# MODULUS : gives us the remainder 

arr2 % arr1

array([0, 1, 0])

In [39]:
# EXPONENTS : squaring the arrays 

arr1 ** arr2 

array([  1,  32, 729])

##### Some built - in mathematical functions 

In [40]:
arr = np.array([1, 4, 9, 16])

In [41]:
# Square - root  : np.sqrt()

np.sqrt(arr)

array([1., 2., 3., 4.])

In [42]:
# Exponential : np.exp()
print (np.exp([1, 2]))      # will print e raised to 1 and 2

[2.71828183 7.3890561 ]


In [43]:
# Trigonometric functions 

angles = np.array([0, np.pi, np.pi/2])
np.sin(angles)                               # will print an array 

# print(np.sin(angles))                          # will print a list 

array([0.0000000e+00, 1.2246468e-16, 1.0000000e+00])

##### Accessing and Slicing Arrays :  

In [44]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr[1]       # will print the row at index = 1 

array([4, 5, 6])

In [46]:
arr[1,1]    # will print the number at index 1 of row at index 1

np.int64(5)

In [47]:
arr[0:2]     # [inclusive, not inclusive]

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
arr =  np.array([10, 20, 30, 40, 50, 60])
arr

array([10, 20, 30, 40, 50, 60])

In [49]:
arr[::2]                #  [starting, len(index), step) ; from starting to ending but step value is 2

array([10, 30, 50])

In [50]:
# Negative indexing : will count from backwards 

arr[-2]

np.int64(50)

In [51]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
matrix[0:2, 0:3]      # row, column

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
matrix[0:3, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [54]:
matrix[1:, 1:]   # row 2 and 3 but excluding column 1

array([[5, 6],
       [8, 9]])

##### Iterations :

In [55]:
# using nditer()

arr = np.array([[1,2,3,4],
                [5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
for x in np.nditer(arr):
    print(x, end='') 

12345678

In [57]:
# using ndenumerate() : it will tell you both , the index value and the value itself 

for x in np.ndenumerate(arr):
    print(x)



((0, 0), np.int64(1))
((0, 1), np.int64(2))
((0, 2), np.int64(3))
((0, 3), np.int64(4))
((1, 0), np.int64(5))
((1, 1), np.int64(6))
((1, 2), np.int64(7))
((1, 3), np.int64(8))


In [58]:
# Transpose of a matrix :

matrix = np.array([[1,2,3,4,5],
                   [6,7,8,9,10]])
matrix 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [59]:
matrix.transpose()

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

##### Concatenation :

In [60]:
a = np.array([[1,2,3,4],
             [5,6,7,8]])

b = np.array([[10,20,30,40],
              [50,60,70,80]])

In [61]:
np.concatenate((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

In [62]:
np.hstack((a,b))     # horizontal addition of the arrays 

array([[ 1,  2,  3,  4, 10, 20, 30, 40],
       [ 5,  6,  7,  8, 50, 60, 70, 80]])

In [63]:
# Repeating the values 

arr = np.array([1,2,3,4])

np.repeat(arr,2)                   # will repeat each elements twice 

array([1, 1, 2, 2, 3, 3, 4, 4])

In [64]:
# Tile : will repeat the whole array 

np.tile(arr,2)

array([1, 2, 3, 4, 1, 2, 3, 4])

##### Aggregate functions : used to summarise the array

In [65]:
arr = np.array([2,4,6,8,10])
arr

array([ 2,  4,  6,  8, 10])

In [66]:
np.sum(arr)             # will give you the sum of all the elements 

np.int64(30)

In [67]:
# to find mean 
np.mean(arr)

np.float64(6.0)

In [68]:
# to find median 
np.median(arr)

np.float64(6.0)

In [69]:
# to find standard deviation :
np.std(arr)

np.float64(2.8284271247461903)

In [70]:
#  to find the variance 
np.var(arr)

np.float64(8.0)

In [71]:
# minimum and maximum values in the array 

np.min(arr)

np.int64(2)

In [72]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
# to find sum accross axes :
# axis = 0 is row 
# axis = 1 is column 

np.sum(matrix, axis=0) 

array([12, 15, 18])

In [74]:
# for cumulative sum :

arr = np.array([2,4,6,8])
arr

array([2, 4, 6, 8])

In [75]:
np.cumsum(arr)

array([ 2,  6, 12, 20])

In [76]:
# for cumulative multiplication 

np.cumprod(arr)

array([  2,   8,  48, 384])

##### Handling missing data :

In [77]:
# nan = not a number 

arr = np.array([[1,2,np.nan],
                [3,4,5],
                [np.nan,9,np.nan]])
arr

array([[ 1.,  2., nan],
       [ 3.,  4.,  5.],
       [nan,  9., nan]])

In [78]:
np.isnan(arr)       # will print True , wherever nan is present 

array([[False, False,  True],
       [False, False, False],
       [ True, False,  True]])

In [79]:
# counting nan values :
# False = 0
# True = 1

np.count_nonzero(np.isnan)

np.int64(1)